# coding=utf-8

''' 环境准备：
    1. IDE下调试路径与执行路径不同，导致找不到module
        sudo sh -c 'echo /mnt/hgfs/local/deploy/fabric > /home/long/.pyenv/versions/3.6.5/lib/python3.6/site-packages/fabric_test.pth'
'''

''' http://docs.fabfile.org/en/2.0/cli.html
    http://docs.pyinvoke.org/en/latest/invoke.html#inv

    https://github.com/pyinvoke/invoke/issues/471
'''